services:
  app:
    build: .
    container_name: python-server
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8001:8000
      - 5678:5678
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:alpine